name: Crawl cf.gov

# Triggers the workflow every day at 6AM UTC (1AM EST, 2AM EDT)
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous crawl results
        run: rm -r www.consumerfinance.gov

      - name: Run the crawl script
        run: ./crawl.sh

      - name: Commit crawl results back to GitHub
        if: always()
        run: ./commit_results.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
