name: Crawl cf.gov

# Test: run at 3:25pm EST (7:25pm UTC)
on:
  schedule:
    - cron: '25 19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: ./crawl.sh

      - name: Commit crawl results back to GitHub
        uses: EndBug/add-and-commit@v4
        with:
          add: www.consumerfinance.gov
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
