name: Crawl cf.gov

# Triggers the workflow every day at 6AM UTC (1AM EST, 2AM EDT)
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous crawl results
        run: rm -r www.consumerfinance.gov

      - name: Run the crawl script
        run: ./crawl.sh
        continue-on-error: true

      - name: Remove <script> tags from crawl results
        run: find www.consumerfinance.gov -type f -exec sed -f 'sed/remove_scripts.sed' -i '' {} \;
        continue-on-error: true

      - name: Prepare COMMIT_MESSAGE variable
        run: ./generate_summary.sh
        continue-on-error: true

      - name: Commit crawl results back to GitHub
        uses: EndBug/add-and-commit@v5
        with:
          add: 'www.consumerfinance.gov'
          author_name: Automated
          author_email: actions@users.noreply.github.com
          message: ${{ env.COMMIT_MESSAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
