name: Crawl cf.gov

# Triggers the workflow every day at 6AM UTC (1AM EST, 2AM EDT)
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Remove previous crawl results
        run: rm -r www.consumerfinance.gov

      - name: Run the crawl script
        run: ./crawl.sh

      - name: Prepare COMMIT_MESSAGE variable
        run: ./generate_summary.sh

      - name: Commit crawl results back to GitHub
        if: always()
        uses: EndBug/add-and-commit
        with:
          add: 'www.consumerfinance.gov'
          author_name: Automated
          author_email: actions@users.noreply.github.com
          message: $COMMIT_MESSAGE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
